version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672" # Porta padrão do AMQP para clientes
      - "15672:15672" # Porta do painel de gerenciamento (opcional, mas útil)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi_app:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq # Nome do serviço no Docker Compose
      RABBITMQ_PORT: 5672
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 # Já definido no Dockerfile
    restart: on-failure

  consumer:
    build: ./consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    restart: on-failure